config/routes.rb
Rails.application.routes.draw do

	resources :messages
	root 'home#index'

	devise_for :users, path: 'utilisateur'
	resources :charges, only: [:new, :create, :confirm_page]

	resources :users
	resources :aircraft

	post "/recherche-de-vol", to: "aircraft#search_results", as: :search_results
	get "/mon-vol/:id", to: "aircraft#trip", as: :trip

	get "/aircrafts", to: 'aircraft#index'
	get "/aircraft/:id", to: 'aircraft#show'
	get "/planes", to: 'planes#index'
	get "/confirm_page", to: 'charges#confirm_page'
	get "message_admin", to: 'messages#index_admin'
	get "authentification", to: "users#authentification"
	post "authentification", to: "users#get_authentification"

	as :user do
		get 'users/profile', :to => 'devise/registrations#edit', :as => :user_root
	end
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :user

	  after_create :notify_email

	def notify_email
		ExampleMailer.notify_email(self).deliver
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update]
  before_action :count_message_admin, only: [:show, :index_admin]
  before_action :count_message_user, only: [:index, :create]


  def index
    if !user_signed_in?
      respond_to do |format|
        format.html { redirect_to new_user_session_path }
        flash[:info] = "Veuillez d'abord vous connectez"
      end
    end

    @message = Message.new
    @messages = Message.all
    @users = User.all
    @admin = User.find(1)
  end

  def index_admin
    @message = Message.new
    @messages = Message.all
  end

  def show
    @reponse = Message.new

  end


  def new
    @message = Message.new
  end

  def edit
  end

  def create

    @content = params[:message][:content]
    if current_user.admin == true
      @message = Message.new(user_id: current_user.id, content: @content, dest_id: params[:dest_id])
    else
      @message = Message.new(user_id: current_user.id, content: @content)
    end
    
    respond_to do |format|
      if @message.save
        format.html { redirect_to request.referrer }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @message.update(user_id: current_user.id, content: @content)
        format.html { redirect_to @message }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    respond_to do |format|
      format.html { redirect_to request.referrer}
      format.json { head :no_content }
    end
  end

  def count_message_admin

    @newmess_admin = []
    @unread_messages = []
    @admin = User.find(1)
    @mess = Message.all
    @mess.each do |mess|
      if mess.user_id != 1
        if ((@admin.messages.where(dest_id: mess.user_id)).last)== nil && mess != nil
          @newmess_admin << "#"
          @unread_messages << mess
          if ((@admin.messages.where(dest_id: mess.user_id)).last)!= nil && mess != nil
            if ((@admin.messages.where(dest_id: mess.user_id)).last).created_at < mess.created_at
              @newmess_admin << "#"
              @unread_messages << mess
            end
          end
        end
      end
    end
    return @newmess_admin.length
  end


  def count_message_user

      # @newmess_user = []
      # @unread_messages = []
      # @admin = User.find(1)
      # @mess = Message.all
      # @mess.each do |mess|
      #   if mess.user_id != 1
      #     if @admin.messages.where(dest_id: mess.user_id).last.created_at < mess.created_at
      #       @newmess_user << "#"
      #       @unread_messages << mess
      #     end
      #   end
      # end
      # return @newmess_user.length

    end



    private

    def set_message

      if User.find(current_user.id).admin == true
       @messages = (User.find(params[:id])).messages
       @reponses = Message.all
     else
      @messages = (User.find(current_user.id)).messages
      @message = Message.find(params[:id])
      @reponses = Message.all
    end
  end

  def message_params
    params.require(:message).permit(:user_id, :content)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_with(model: message, local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<div style="margin-top: 10">
	 

<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

</div>

app/views/messages/index.html.erb
<% if user_signed_in? %>

<p id="notice" style="margin-top: 10%"> <% notice %></p>
<div class="display_mess" style="margin-bottom:15% ">
  <!-- TABLEAU DE MESSAGERIE-->
  <h1>Messagerie</h1>
  <table class="table table-striped table-bordered" style="width:100%">
    <th> <%= current_user.last_name.capitalize %></th>
    <th></th>
    <th>Administrateur</th>
    <th id="date_message">Date</th>
    <tbody>
      <% @messages_to_display = []%>
      <% @messages.each do |message| %>
      <% if message.user_id == current_user.id %>
      <%@messages_to_display << message %>
      <% end %>
      <% end %>
      <% @admin.messages.each do |message| %>
      <% if message.dest_id == current_user.id %>
      <%@messages_to_display << message %>
      <% end %>
      <% end %>
      <br>
      <tr>
        <% @messages_to_display.each do |message| %>
        <% if message.user_id == current_user.id %>
        <td><%= message.content %></td>
        <td><%= link_to 'Supprimer', message, method: :delete, data: { confirm: 'Are you sure?' } %>

          <td></td>
          <% else %>
          <td></td>
          <td></td>
          <td><%= message.content %></td>
          <%end%>
          <td><%= message.created_at.to_s.delete("UTC")%></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <!-- FIN TABLEAU-->
  <!-- FORMULAIRE DE REPONSE-->

  <div id="form_mess" class="form_mess">
    <%= form_with(model: @message, local: true) do |form| %>
    <div class="field">
      <%= form.label :content %>
      <%= form.text_area :content, id: 'message_tag' %>
      <div class="actions">
        <%= form.submit %>
      </div>
      <% end %>
    </div>
  </div>
  <!-- FIN DU FORMULAIRE-->
  <!-- SCRIPT POUR CLASSER SELON LA DATE-->
  <script>
    $(document).ready(function () {
     var table = $('table');
     $('#date_message')
     .wrapInner('<span title="sort this column"/>')
     .each(function(){
      var th = $(this),
      thIndex = th.index(),
      inverse = false;
      th.ready(function () {
        table.find('td').filter(function(){
          return $(this).index() === thIndex;
        }).sortElements(function(a, b){
          return $.text([a]) > $.text([b]) ?
          inverse ? -1 : 1
          : inverse ? 1 : -1;
        }, function(){
          return this.parentNode; 
        });
        inverse = !inverse;
      });
    });
   });
 </script>
<%end%>

 <!-- FIN DU SCRIPT -->

app/views/messages/index_admin.html.erb
<!-- PAGE MESSAGERIE ADMIN-->


<% if current_user.admin == true %>
<p id="notice" style="margin-top: 10%"> <% notice %></p>
<div class="display_mess">

  <!-- permet d'afficher un bouton qui indique les nouveaux messages -->



  <% if  @newmess_admin.count >= 1 %>
  <button type="button" class="btn btn-success" data-toggle="modal" data-target=".bd-example-modal-sm"> 
    <% if  @newmess_admin.count == 1%>
    <%= @newmess_admin.count %> Message non lu</button>
    <% else %>
    <%= @newmess_admin.count %> Messages non lus</button>
    <% end %>
    <div class="modal fade bd-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-sm">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">
              Vous avez <%= @newmess_admin.count%> Messages non lus
            </h4>
          </div>
          <div class="modal-body">

            <% @unread_messages.each do |message| %>

            <td>de :<%= message.user %> :</td> <br>

            <td>Message Content : <%= message.content %></td><br>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <% else %>
    <button type="button" class="btn btn-primary mb-2 mr-1" data-toggle="modal" data-target=".bd-example-modal-sm">Pas de nouveau message</button>
    <% end %>



    <!-- Fin d''affichage -->







    <!-- Tableau de messagerie -->
    <div>
      <h1>Messages de: </h1>
      <table class="table table-striped table-bordered" style="width:100%">
        <tbody>
          <% @issuer = []%>
          <% @issuer_id = []%>

          <% @messages.each do |message| %>
          <% if message.user_id != nil%>
          <% @issuer << User.find(message.user_id).last_name %>
          <% @issuer_id << message.user_id %>
          <% end %>
          <% end %>
          <%  deliverer = @issuer.uniq %>
          <%  deliverer_id = @issuer_id.uniq %>
          <% deliverer_and_id = Hash[deliverer.zip(deliverer_id)]%>
          <tr>
           <%  deliverer_and_id.each do |first_name, id|%>
           <% if first_name != current_user.last_name %>
           <% if id != current_user.id %>
           <td><%= first_name.capitalize %> </td>
           <td><%= link_to 'Show', message_path(id, name: first_name) %></td>
         </tr>
         <% end %>
         <% end %>
         <% end %>
       </tbody>
     </table>
   </div>

 </div>
 <!-- Fin du tableau de messagerie -->

 <% else %>
 <!-- Alternative a la page ADMIN -->
 <div style="margin-top: 20%">
  <h1>Vous allez etre redirigé</h1>
</div>
<!-- END page protégée ADMIN -->
<% end %>

app/views/messages/show.html.erb
<!--PAGE SHOW MESSAGERIE ADMIN-->

<div style="margin-top: 10%" >
	<a class="btn btn-primary" href="<%= message_admin_path %>" role="button"> < Boite de reception</a>
	<div class="portlet-body no-padding">
		<br>

		


		<!-- TABLEAU MESSAGERIE -->
		<h1>Messages Recus de <%=(params[:name]).capitalize%></h1>
		<table class="table table-striped table-bordered" style="width:100%">
			<th><%=User.find(params[:id]).last_name.capitalize%></th>
			<th><%= current_user.last_name.capitalize %></th>
			<th id="date_message">Date</th>
			<tbody>
				<% @messages_to_display = [] %>
				<% @messages.each do |message| %>
				<% @messages_to_display << message %>
				<% end %>
				<% @reponses.each do |reponse| %>
				<% if (reponse.dest_id).to_i == (params[:id]).to_i %>
				<% @messages_to_display << reponse %>
				<% end %>
				<% end %>
				<tr>
					<% @messages_to_display.each do |message|%>
					<% if message.user_id != current_user.id %>
					<td><%= message.content %></td>
					<td></td>
					<% else %>
					<td></td>
					<td><%= message.content %></td>
					<% end %>
					<td><%= message.created_at.to_s.delete("UTC")%></td>
				</tr>
				<% end %>
			</tbody>	
		</table>
	</div>
</div>
<!-- FIN DU TABLEAU MESSAGERIE -->
<!-- FORMULAIRE DE REPONSE -->
<div class="form_mess">
	<%= form_with(model: @reponse, local: true) do |form| %>
	<div class="field">
		<%= form.label :content, "Saisisssez votre message :" %>
		<%= form.text_area :content, id: 'message_tag' %>

		<%= hidden_field_tag "dest_id", params[:id] %>
		<div class="actions">
			<%= form.submit %>
		</div>
		<% end %>
	</div>
</div>
<!-- FIN FORMULAIRE -->
<!-- SCRIPT POUR METTRE LES MESSAGES EN FONCTION DE LEUR DATE-->
<script>
	$(document).ready(function () {
		var table = $('table');
		$('#date_message')
		.wrapInner('<span title="sort this column"/>')
		.each(function(){
			var th = $(this),
			thIndex = th.index(),
			inverse = false;
			th.ready(function () {
				table.find('td').filter(function(){
					return $(this).index() === thIndex;
				}).sortElements(function(a, b){
					return $.text([a]) > $.text([b]) ?
					inverse ? -1 : 1
					: inverse ? 1 : -1;
				}, function(){
					return this.parentNode; 
				});
				inverse = !inverse;
			});
		});
	});
</script>
<!-- FIN DU SCRIPT -->