config/routes.rb
Rails.application.routes.draw do

	resources :messages
	root 'home#index'

	devise_for :users, path: 'utilisateur'
	resources :charges, only: [:new, :create, :confirm_page]

	resources :users
	resources :aircraft

	post "/recherche-de-vol", to: "aircraft#search_results", as: :search_results
	get "/mon-vol/:id", to: "aircraft#trip", as: :trip

	get "/aircrafts", to: 'aircraft#index'
	get "/aircraft/:id", to: 'aircraft#show'
	get "/planes", to: 'planes#index'
	get "/confirm_page", to: 'charges#confirm_page'
	get "message_admin", to: 'messages#index_admin'
	get "authentification", to: "users#authentification"
	post "authentification", to: "users#get_authentification"

	as :user do
		get 'users/profile', :to => 'devise/registrations#edit', :as => :user_root
	end
end

app/models/user.rb
require 'nexmo'

class User < ApplicationRecord

  has_many :user_flights
  has_many :messages

  mount_uploader :avatar, AvatarUploader

  def transform(value)
    if value.size != 10 
     if value.size <= 10
      a = 10 - value.size
      value = value + ("0" * a)
      puts value
    else
      value = value.slice(1..10)
    end
  end
  return value
end

devise :database_authenticatable, :registerable,
:recoverable, :rememberable, :validatable

  # before_save { self.phone = transform(self.phone) }
  @datetime = DateTime.now

 after_create :send_email


  def send_email
  	ExampleMailer.send_email(self).deliver    
  end

  def validity(number)
    if number.length == 10 && number.start_with?("06") || number.length == 10 && number.start_with?("07") || number.length == 11 && number.start_with?("33")
      true
    end
  end

  def self.send_sms(phone_number, user)
    client = Nexmo::Client.new(api_key: ENV['api_key'], api_secret: ENV['api_secret'])
    client.sms.send(from: 'Stratton', to: "#{phone_number}", text: "Stratton code : #{user.code_confirm}. Valable pendant 3 minutes")
    puts "NEXMO MESSAGE ENVOYÉ"
  end

  def self.verification(user, number)
   if user.code_confirm == nil || user.updated_at < DateTime.now - 1.minutes
    user.code_confirm = rand(1000..9999)
    user.save
    send_sms(number, user)
  else
    puts "user.code_confirm existe deja"
  end
  if @text.to_i == user.code_confirm
    user.verified = true
    user.save
  end
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user

	def show 
		@user = current_user
	end

	def edit
	end

	def create
	end

	def authentification
		puts "AUTHENTIFICATION"
		if @user.phone != nil
			if @user.phone.start_with?("06") || @user.phone.start_with?("07")
				@nexmo  = @user.phone.sub(/^./, "33")
				User.verification(@user, @nexmo)
			end
		end
	end

	def get_authentification
		if params[:new] != nil
			@user.phone = params[:new]
			@user.save
		elsif params[:text] != nil
			if params[:text].to_i == @user.code_confirm
				@user.verified = true
				@user.save	
			end			
		end
		respond_to do |format|
			format.html { redirect_to request.referrer}
		end	
	end

	private

	def set_user
		@user = current_user
	end

end

app/helpers/users_helper.rb
module UsersHelper



	
	

	
end

app/views/users/authentification.html.erb
<div style="margin-top: 10%">
	<% if @user.verified == true %>
	<h2>Votre numero de téléphone est verifié.</h2>
	<a><%= link_to "Retour", user_path(current_user), class: "btn btn-success"  %></a>
	<%elsif%>
	<% @user.validity(@user.phone) == true %>
	<h1>Vous voila sur la page pour verifier votre numero de telephone</h1>
	<h2>
		Tapez ici le code secret qui vient d'etre envoyé sur votre mobile, dont le numero est : <%= @user.phone %> <br>
		Il sera renouvelé d'ici 3 minutes <br>
		<br>
		<%= form_tag url_for(action: 'authentification') do %>
		<div class="field">
			<%= text_field_tag 'text' %>
			<div class="actions">
				<br>
				<%= submit_tag "send" %>
			</div>
			<% end %>
		</div>
		<h4>Si vous souhaitez changer de numero de telephone :</h4> 
		<%= form_tag url_for(action: 'authentification'), method: "post" do %>
		<div class="field">
			<%= text_field_tag 'new' %>
			<div class="actions">
				<br>
				<%= submit_tag "send" %>
			</div>
			<% end %>
		</div>
	</h2>
	<%else%>
	<h2> Desole, <br> <%= @user.phone%> ne semble pas etre un numero de telephone valide. S'il vous plait veuillez indiquer un numero de telephone sur lequel vous pouvez recevoir des appels et des sms. </h2>
	<%= form_tag url_for(action: 'authentification'), method: "post" do %>
	<div class="field">
		<%= text_field_tag 'new' %>
		<div class="actions">
			<br>
			<%= submit_tag "send" %>
		</div>
		<% end %>
	</div>
	<%end%>
</div>

app/views/users/show.html.erb
<div class="center jumbotron", style="margin-top: 3%">
	<div style="float: right; font-size: 20px">
	</div>
	<div class="col-lg-3 col-md-6 mb-30" style="float: left;">
		<div class="bg-white shadow-sm rounded overflow-hidden">
			<div class="avatar">
				<%=image_tag  @user.avatar.url(:thumb) if @user.avatar? %>
				<br>
			</div>
			<h3 class="text-center text-dark pt-15"><%= @user.first_name.capitalize %> <%= @user.last_name.capitalize %></h3>
			<div class="clearifx row no-margin pt-3 pb-3">
				<a class="col-4 text-center">
					<i class="icon-Plane"></i><br>
					<span class="pt-1 text-dark text-muted fs-1x text-primary"><%= @user.user_flights.count%></span><br>
					<span class="pt-1 fs12">Vols</span>
				</a>
				<a class="col-4 b-r b-l text-center">
					<i class="fa fa-history"></i><br>
					<span class="pt-1 text-dark text-muted fs-1x text-primary">30</span><br>
					<span class="pt-1 fs12">Heures de vol</span>
				</a>
				<a class="col-4 text-center">
					<i class="icon-Speaker fs-1x"></i><br>
					<% total_km = [] %>
					<% @user.user_flights.each do |flights| %>
					<% total_km << Airport.km_between_airports(flights.place_departure, flights.place_arrival) %>
					<% end %>
					<span class="pt-1 text-dark text-muted fs-1x text-primary"><%= total_km.sum.to_i %></span><br>
					<span class="pt-1 fs12">Km parcourus</span>
				</a>
			</div>
		</div>
	</div>
	<div style="float: left;">
		<h3>
			<i class="icon-Paper-Plane"></i>
			<tr>Email : <%= @user.email %> </tr> 
			<br>
			<i class="fa fa-phone"></i>
			<tr>Telephone Personnel : <%= @user.phone %></tr> 
			<% if @user.verified == true %>
			<%= image_tag("check.png", size: "24x24", alt: "Numero vérifié", class: "verified")%>
			<br>
			<% else %>
			<tr><%= link_to "verifier son numero", authentification_path %> </tr> 
			<%end%>
			<br>
			<% if current_user.admin == true %>
			<i class="fa fa-envelope"></i><%= link_to "Boite de reception", message_admin_path %>
			<% else %>
			<tr><i class="fa fa-envelope"></i><%= link_to " Messagerie", messages_path %> </tr> 
			<%end%>
			<br>
			<tr><i class="icon-Gear"></i><%= link_to " Editer son  profil", edit_user_registration_path %> </tr> <br>
		</div>
		<br><br><br><br><br>
		<%if @user.avatar? %>
		<br><br><br><br><br>
		<%end%>
	</h3>
</div>
<div>
	<h2>Liste de vos vols</h2>	
	<table class="table mb-0 table-striped" cellspacing="0" width="100%">
		<thead>
			<tr>
				<th>Reservation faite le</th>
				<th>Vol prevu le</th>
				<th>Au depart de</th>
				<th>Arrivée à</th>
				<th>Nombre de passager</th>
				<th>Cout total du vol</th>
				<th>Km parcouru</th>
				<th>Status</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<% @user.user_flights.each do |flights| %>
				<td><%= flights.created_at.strftime("%d/%m/%Y")  %></td>
				<%if flights.date_departure == nil %>
				<td><%= Date.today.strftime("%d/%m/%Y")%></td>
				<%else%>
				<td><%= flights.date_departure.strftime("%d/%m/%Y")  %></td>
				<%end%>
				<td><%= flights.place_departure  %></td>
				<td><%= flights.place_arrival %></td>
				<td><%= flights.number_of_people %></td>
				<td><%= flights.flight_price.to_i%>€</td>
				<td><%= Airport.km_between_airports(flights.place_departure, flights.place_arrival) %> kms</td>
				<%if flights.date_departure != nil %>
				<% if flights.date_departure <= Date.today %> 
				<td>effectué</td>
				<% else %> 
				<td>à venir</td>
				<% end %>
				<% else %> 
				<td>à venir</td>
				<% end %> 
			</tr>
			<%end%>
			<tr>
				<th></th>
				<th></th>
				<th></th>
				<th></th>
				<th></th>
				<th>Cout total des vols</th>
				<th></th>
				<th></th>
			</tr>
			<tr>
				<% total_price = [] %>
				<% @user.user_flights.each do |flights| %>
				<% total_price << flights.flight_price.to_i %>
				<% end %>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td class="eur"><%= total_price.sum %>€</td>
				<td></td>
				<td></td>
			</tr>
		</tbody>
	</table>
</div>