config/routes.rb
Rails.application.routes.draw do

	resources :messages
	root 'home#index'

	devise_for :users, path: 'utilisateur'
	resources :charges, only: [:new, :create, :confirm_page]

	resources :users
	resources :aircraft

	post "/recherche-de-vol", to: "aircraft#search_results", as: :search_results
	get "/mon-vol/:id", to: "aircraft#trip", as: :trip

	get "/aircrafts", to: 'aircraft#index'
	get "/aircraft/:id", to: 'aircraft#show'
	get "/planes", to: 'planes#index'
	get "/confirm_page", to: 'charges#confirm_page'
	get "message_admin", to: 'messages#index_admin'
	get "authentification", to: "users#authentification"
	post "authentification", to: "users#get_authentification"

	as :user do
		get 'users/profile', :to => 'devise/registrations#edit', :as => :user_root
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_booking_alt.html.erb
<div class="pt100 pb70 parallax-overlay bg-parallax" data-jarallax="{&quot;speed&quot;: 0.4}" id= "booking" >
	<div class="container">
		<div class="row newsletter-row">
			<div class="col-lg-10 mr-auto m-auto mb30 text-center">
				<div class="center-title mb60 text-center">
					<h2 class="text-white">Veuillez vous connecter</h2>
					<p class="text-white-gray"> La technologie Stratton est reservée à nos membres</p>
					<br><br>


				</div>
				<li class="nav-item" style="list-style: none; float: left; margin-left: 30%"><a>

	<%= link_to "Log in", new_user_session_path,  class: "btn btn-xl btn-primary"  %></a></li>



<li class="nav-item" style="list-style: none;float: right; margin-right: 30%"><a><%= link_to "Sign up", new_user_registration_path, class: "btn btn-xl btn-primary"  %></a></li>
			</div>
		</div>
	</div>
</div>
<div id="jarallax-container-3">
	<div id="jarallax-container-3-bis" style="background-image: url('<%= asset_path 'travel.jpg' %>');">
	</div>
</div>

app/views/home/_booking_good.html.erb
<div class="pt100 pb70 parallax-overlay bg-parallax" data-jarallax="{&quot;speed&quot;: 0.4}" id= "booking" >
<div class="container">
	<div class="row newsletter-row">
		<div class="col-lg-10 mr-auto m-auto mb30 text-center">
			<div class="center-title mb60 text-center">
				<h2 class="text-white">Votre réservation</h2>
				<p class="text-white-gray"></p>
			</div>
			<%= form_tag search_results_path do%>
			<div class="row">
				<div id="book_tag" class="form-group">
					<%= label_tag :departure_city, "De :"  %>
					<%= select_tag :departure_city, options_for_select(Airport.all_airports_city_code_array), class: 'form-control', id: 'select_tag' %>
				</div>
				<div class="form-group" id="book_tag">
					<%= label_tag :arrival_city, "À :" %>
					<%= select_tag :arrival_city, options_for_select(Airport.all_airports_city_code_array), class: 'form-control', id: 'select_tag' %>
				</div>

				<div class="form-group" id="book_tag">
					<%= label_tag :departure_date, "Départ :" %>
					<%= text_field_tag :departure_date, nil, placeholder: "dd/mm/yyyy", id: "checkin", class: 'form-control form-control-lg datepicker' %>
				</div>
				<div class="form-group" id="book_tag">
					<%= label_tag :number_of_passengers, "Passager(s) :" %>
					<%= number_field_tag :number_of_passengers, nil, placeholder: 'Beetween 1-16 persons', class: 'form-control' %>
					<br>
				</div>
				<div class="search" style="margin-left: 42%">
					<%= submit_tag "Rechercher", class: "btn btn-primary" %>
				</div>
			</div>
			<% end %>
		</div>
	</div>
</div>
</div>
<div id="jarallax-container-3">
	<div id="jarallax-container-3-bis" style="background-image: url('<%= asset_path 'travel.jpg' %>');">
	</div>
</div>

app/views/home/_caroussel.html.erb
<div id="white">
	<div class="container" >
		<div class="center-title">
			<br><br>
			<h2 class="text-black">Le monde des jets privés</h2>
			<p class="text-black"></p>
		</div>
		<div class="row">
			<div class="owl-carousel owl-theme carousel-cards">

				<div class="item">
					<center>
						<a class="card-image">
							<%= image_tag('light.png', :class => 'img-fluid') %>
							<h5>Light Jet</h5>
						</a>
					</center>
				</div><!--item-->

				<div class="item">
					<center>
						<a class="card-image" >
							<%= image_tag('midsize.jpg', :class => 'img-fluid') %>
							<h5>Midsize Jet</h5>
						</a>
					</center>
				</div><!--item-->

				<div class="item">
					<center>
						<a class="card-image">
							<%= image_tag('heavy.jpeg', :class => 'img-fluid') %>
							<h5>Heavy Jet</h5>
						</a>
					</center>
				</div>


			</div>
		</div>
	</div>

	<br><br><br><br>
</div>

app/views/home/_comparatif.html.erb
<div id="white_margin">
	<div id="comp" class="center-title">
		<h2 class="text-black" >Notre Programme</h2>
	</div>
	<div id="page">
		<section id="margin_m10" class="comp-table padded">
			<div class="regular-container">
				<div class="row">
					<div class="col-md-4 col-xs-12 legend-col">
					</div>
					<div class="col-md-offset-4 col-md-4 col-xs-6 opendoor-col">
						<center>
							<h2 class="text-white medium-margin-top">Stratton <br><br></h5>
							</center>
							<div class="fees-label">
								<div class="percentage">5% </div> Commission fixe
							</div>
						</div>
						<div class="col-md-4 col-xs-6 traditional-sale-col">
							<center>
								<h2 class="medium-margin-top">Courtier Traditionnel</h5>
								</center>
								<div class="fees-label"><div class="percentage">10-20% </div> Commission variable</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-4 col-xs-12 legend-col">
								<p class="text-muted">Vol Paris - Londres, 6 personnes <br> (Avion de catégorie "Midsize")</p>
							</div>

							<div class="col-md-4 col-xs-6 opendoor-col">
								<div class="price">11 000 € </div>
							</div>

							<div class="col-md-4 col-xs-6 traditional-sale-col">
								<div class="price">11 000 € </div>
							</div>
						</div>

						<div class="row">
							<div class="col-md-4 col-xs-12 legend-col">
								<p class="text-muted">Montant de la commission</div>

							<div class="col-md-4 col-xs-6 opendoor-col">
								<div class="price">550 € </div>
							</div>

							<div class="col-md-4 col-xs-6 traditional-sale-col">
								<div class="price">1100 € à 2200 € </div>
							</div>
						</div>



						<div class="row">
							<div class="col-md-4 col-xs-12 legend-col">
								<h4 class="legend-title">Transparence</h4>
							</div>
							<div class="col-md-4 col-xs-6 opendoor-col hidden-sm-down empty-cell">
								&nbsp;
							</div>
							<div class="col-md-4 col-xs-6 traditional-sale-col hidden-sm-down empty-cell">
								&nbsp;
							</div>
						</div>
						<div class="row">
							<div class="col-md-4 col-xs-12 legend-col">
								<p>Prix instantané</p>
							</div>
							<div class="col-md-4 col-xs-6 opendoor-col">
								<div class="value">✓ Oui </div>
							</div>
							<div class="col-md-4 col-xs-6 traditional-sale-col">
								<div class="value">✘ Non </div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-4 col-xs-12 legend-col">
								<p>Nom de la compagnie</p>
							</div>
							<div class="col-md-4 col-xs-6 opendoor-col">
								<div class="value">✓ Oui </div>
							</div>
							<div class="col-md-4 col-xs-6 traditional-sale-col">
								<div class="value">✘ Non </div>
							</div>
						</div>
						<div class="row">
						<div class="col-md-4 col-xs-12 legend-col">
							<p>Nationalité de la compagnie</p>
						</div>
						<div class="col-md-4 col-xs-6 opendoor-col">
							<div class="value">✓ Oui </div>
						</div>
						<div class="col-md-4 col-xs-6 traditional-sale-col">
							<div class="value">✘ Non </div>
						</div>
					</div>
						<div class="row">
							<div class="col-md-4 col-xs-12 legend-col"><p>Immatriculation de l'avion</p>
							</div>
							<div class="col-md-4 col-xs-6 opendoor-col">
								<div class="value">✓ Oui </div>
							</div>
							<div class="col-md-4 col-xs-6 traditional-sale-col">
								<div class="value">✘ Non </div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-4 col-xs-12 legend-col">
								<h4 class="legend-title">Technologie</h4>
							</div>
							<div class="col-md-4 col-xs-6 opendoor-col hidden-sm-down empty-cell">
								&nbsp;
							</div>
							<div class="col-md-4 col-xs-6 traditional-sale-col hidden-sm-down empty-cell">
								&nbsp;
							</div>
						</div>
						<div class="row">
							<div class="col-md-4 col-xs-12 legend-col">
								<p>Plateforme technologique de réservation</p>
							</div>
							<div class="col-md-4 col-xs-6 opendoor-col">
								<div class="value">✓ Oui </div>
							</div>
							<div class="col-md-4 col-xs-6 traditional-sale-col">
								<div class="value">En fonction de votre courtier</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-4 col-xs-12 legend-col">
								<p>Application dédiée</p>
							</div>
							<div class="col-md-4 col-xs-6 opendoor-col">
								<div class="value">✓ Oui </div>
							</div>
							<div class="col-md-4 col-xs-6 traditional-sale-col">
								<div class="value">En fonction de votre courtier</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-4 col-xs-12 legend-col">
								<p>Assistant dédié</p>
							</div>
							<div class="col-md-4 col-xs-6 opendoor-col">
								<div class="value">✓ Oui </div>
							</div>
							<div class="col-md-4 col-xs-6 traditional-sale-col">
								<div class="value">En fonction de votre courtier</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-4 col-xs-12 legend-col">
								<h4 class="legend-title">RSE</h4>
							</div>
							<div class="col-md-4 col-xs-6 opendoor-col hidden-sm-down empty-cell">
								&nbsp;
							</div>
							<div class="col-md-4 col-xs-6 traditional-sale-col hidden-sm-down empty-cell">
								&nbsp;
							</div>
						</div>
						<div class="row">
							<div class="col-md-4 col-xs-12 legend-col">
								<p>Dématérialisation</p>
							</div>
							<div class="col-md-4 col-xs-6 opendoor-col">
								<div class="value">✓ Oui </div>
							</div>
							<div class="col-md-4 col-xs-6 traditional-sale-col">
								<div class="value">En fonction de votre courtier</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-4 col-xs-12 legend-col">
								<p>Compensation carbone</p>
							</div>
							<div class="col-md-4 col-xs-6 opendoor-col">
								<div class="value">✓ Oui </div>
							</div>
							<div class="col-md-4 col-xs-6 traditional-sale-col">
								<div class="value">En fonction de votre courtier</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-4 col-xs-12 legend-col">
								<h4 class="legend-title">Coût total du vol</h4>
							</div>
							<div class="col-md-4 col-xs-6 opendoor-col">
								<div class="price small-margin-top small-margin-bottom">11 650 € </div>
							</div>
							<div class="col-md-4 col-xs-6 traditional-sale-col">
								<div class="price small-margin-top small-margin-bottom">12 100 € à 14 200 €</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-4 col-xs-12 legend-col">
								<h4 class="legend-title">Économie réalisée</h4>
							</div>
							<div class="col-md-4 col-xs-6 opendoor-col">
								<div class="price small-margin-top small-margin-bottom"> 450 € à 2550 €</div>
							</div>
							<div class="col-md-4 col-xs-6 traditional-sale-col">
								<div class="price small-margin-top small-margin-bottom"></div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-4 col-xs-12 legend-col hidden-sm-down">
								<div class="empty-cell">&nbsp;</div>
							</div>

						</div>
					</div>
				</section>
			</div>
		</div>

app/views/home/_comparatif1.html.erb
<div style="background-color: white;  margin-bottom: -10%;">
	<br><br><br><br><br>
	<div id="comp" class="center-title">
		<h2 class="text-black" >Tableau Comparatif</h2>
	</div>
	<div id="page" style="font-size: 130%">
		<section class="comp-table padded" style="margin-top: -10%;">
			<div class="regular-container">
				<div class="row">
					<div class="col-md-4 col-xs-12 legend-col">
					</div>
					<div class="col-md-offset-4 col-md-4 col-xs-6 opendoor-col">
						<center>
							<h2 class="text-white medium-margin-top">Stratton <br><br></h5>
							</center>
							<div class="fees-label">
								<div class="percentage">5% </div> Commission fixe
							</div>
						</div>
						<div class="col-md-4 col-xs-6 traditional-sale-col">
							<center>
								<h2 class="medium-margin-top">Courtier Traditionnel</h5>
								</center>
								<div class="fees-label"><div class="percentage">10-20% </div> Commission variable</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-4 col-xs-12 legend-col">
								<p class="text-muted">Vol Paris - Londres, 6 personnes <br> (Categorie "Midsize")</p>
							</div>

							<div class="col-md-4 col-xs-6 opendoor-col">
								<div class="price">11 000 </div>
							</div>

							<div class="col-md-4 col-xs-6 traditional-sale-col">
								<div class="price">11 000</div>
							</div>

						</div>
						<div class="row">
							<div class="col-md-4 col-xs-12 legend-col">
								<h4 class="legend-title">Réservation</h4>
							</div>
							<div class="col-md-4 col-xs-6 opendoor-col hidden-sm-down empty-cell">
								&nbsp;
							</div>
							<div class="col-md-4 col-xs-6 traditional-sale-col hidden-sm-down empty-cell">
								&nbsp;
							</div>
						</div>
						<div class="row">
							<div class="col-md-4 col-xs-12 legend-col">
								<p>Prix instantané</p>
							</div>
							<div class="col-md-4 col-xs-6 opendoor-col">
								<div class="value">✓ Oui </div>
							</div>
							<div class="col-md-4 col-xs-6 traditional-sale-col">
								<div class="value">✘ Non </div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-4 col-xs-12 legend-col">
								<p>Nom de la compagnie</p>
							</div>
							<div class="col-md-4 col-xs-6 opendoor-col">
								<div class="value">✓ Oui </div>
							</div>
							<div class="col-md-4 col-xs-6 traditional-sale-col">
								<div class="value">✘ Non </div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-4 col-xs-12 legend-col"><p>Immatriculation de l'avion</p>
							</div>
							<div class="col-md-4 col-xs-6 opendoor-col">
								<div class="value">✓ Oui </div>
							</div>
							<div class="col-md-4 col-xs-6 traditional-sale-col">
								<div class="value">✘ Non </div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-4 col-xs-12 legend-col">
								<h4 class="legend-title">Technologie</h4>
							</div>
							<div class="col-md-4 col-xs-6 opendoor-col hidden-sm-down empty-cell">
								&nbsp;
							</div>
							<div class="col-md-4 col-xs-6 traditional-sale-col hidden-sm-down empty-cell">
								&nbsp;
							</div>
						</div>
						<div class="row">
							<div class="col-md-4 col-xs-12 legend-col">
								<p>Plateforme technologique de reservation</p>
							</div>
							<div class="col-md-4 col-xs-6 opendoor-col">
								<div class="value">✓ Oui </div>
							</div>
							<div class="col-md-4 col-xs-6 traditional-sale-col">
								<div class="value">En fonction de votre courtier</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-4 col-xs-12 legend-col">
								<p>Application dédiée</p>
							</div>
							<div class="col-md-4 col-xs-6 opendoor-col">
								<div class="value">✓ Oui </div>
							</div>
							<div class="col-md-4 col-xs-6 traditional-sale-col">
								<div class="value">En fonction de votre courtier</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-4 col-xs-12 legend-col">
								<p>Assistant dédiée</p>
							</div>
							<div class="col-md-4 col-xs-6 opendoor-col">
								<div class="value">✓ Oui </div>
							</div>
							<div class="col-md-4 col-xs-6 traditional-sale-col">
								<div class="value">En fonction de votre courtier</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-4 col-xs-12 legend-col">
								<p>A remplir</p>
							</div>
							<div class="col-md-4 col-xs-6 opendoor-col">
								<div class="value">—</div>
							</div>
							<div class="col-md-4 col-xs-6 traditional-sale-col">
								<div class="value">-</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-4 col-xs-12 legend-col">
								<p>A remplir</p>
							</div>
							<div class="col-md-4 col-xs-6 opendoor-col">
								<div class="value">-</div>
							</div>
							<div class="col-md-4 col-xs-6 traditional-sale-col">
								<div class="value">-</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-4 col-xs-12 legend-col">
								<h4 class="legend-title">Écologie</h4>
							</div>
							<div class="col-md-4 col-xs-6 opendoor-col hidden-sm-down empty-cell">
								&nbsp;
							</div>
							<div class="col-md-4 col-xs-6 traditional-sale-col hidden-sm-down empty-cell">
								&nbsp;
							</div>
						</div>
						<div class="row">
							<div class="col-md-4 col-xs-12 legend-col">
								<p>Dématérialisation</p>
							</div>
							<div class="col-md-4 col-xs-6 opendoor-col">
								<div class="value">✓ Oui </div>
							</div>
							<div class="col-md-4 col-xs-6 traditional-sale-col">
								<div class="value">En fonction de votre courtier</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-4 col-xs-12 legend-col">
								<p>Compensation carbone</p>
							</div>
							<div class="col-md-4 col-xs-6 opendoor-col">
								<div class="value">✓ Oui </div>
							</div>
							<div class="col-md-4 col-xs-6 traditional-sale-col">
								<div class="value">En fonction de votre courtier</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-4 col-xs-12 legend-col">
								<h4 class="legend-title">Coût total du vol</h4>
							</div>
							<div class="col-md-4 col-xs-6 opendoor-col">
								<div class="price small-margin-top small-margin-bottom">11 650</div>
							</div>
							<div class="col-md-4 col-xs-6 traditional-sale-col">
								<div class="price small-margin-top small-margin-bottom">12 100 - 14 200</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-4 col-xs-12 legend-col">
								<h4 class="legend-title">Économie réalisée</h4>
							</div>
							<div class="col-md-4 col-xs-6 opendoor-col">
								<div class="price small-margin-top small-margin-bottom"> De 450 à 2550</div>
							</div>
							<div class="col-md-4 col-xs-6 traditional-sale-col">
								<div class="price small-margin-top small-margin-bottom">-</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-4 col-xs-12 legend-col hidden-sm-down">
								<div class="empty-cell">&nbsp;</div>
							</div>

						</div>
					</div>
				</section>
			</div>
		</div>

app/views/home/_footer.html.erb
  <div id="footer">
    <div >
     <span>Support</span>
     <p class="lead">Strattonjets@hotmail.com</p>
     <span>Phone</span>
     <p class="lead">(+33)07 12 34 56 78 </p>
     &copy; Copyright 2018. All Right Reserved.
   </div>
 </div>

 <div id="margin_l">
  <div>
    <a href='#home' data-scroll class='h6'>
      <%= image_tag('logo.png',  width: 140, height: 30, :class => 'logo logo-light hidden-md-down') %>
    </a>  <br>
    La technologie Stratton : générateur de confiance<br>
  </div>
  <br>
  <div>
    <h4>Follow us</h4>
    <span class='clearfix'>
      <a href="https://www.facebook.com/Stratton-Jets-1915637701850443/" class="social-icon-sm si-dark si-dark-round si-facebook">
        <i class="fa fa-facebook"></i>
        <i class="fa fa-facebook"></i>
      </a>
      <a href="https://www.instagram.com/strattonjets/" class="social-icon-sm si-dark si-dark-round si-instagram">
        <i class="fa fa-instagram"></i>
        <i class="fa fa-instagram"></i>
      </a>
    </span>
  </div>
</div>

app/views/home/_navbar.html.erb
<div id="black">
	<nav id="nav" class="navbar navbar-expand-lg navbar-light bg-faded">

		<div class="container" >

			<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarRestaurant" aria-controls="navbarRestaurant" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<a class="navbar-brand" href="index.html">
				<%= image_tag('', :class => 'logo logo-light hidden-md-down') %></a>
				<div  id="navbarRestaurant" class="navbar-collapse collapse" style="margin-bottom: 0.5%;">
					<ul class="navbar-nav  ml-auto">

						<li class="nav-item"><a><%= link_to "Acceuil", root_path, class: "nav-link active"  %></a></li>
						<li class="nav-item"><a data-scroll class="nav-link" href="#vision">Vision</a></li>
						<li class="nav-item"><a data-scroll class="nav-link" href="#comp">Notre Offre</a></li>
						<% if user_signed_in? %>
						<li class="nav-item" >
								<% if current_user.admin == true %>
							<a data-scroll class="nav-link" style="color: #db2e2e !important;">Mode Admin Connecté</a>
								<% else %>
							<a data-scroll class="nav-link" style="color: #db2e2e !important;">Connecté</a>
								<% end %>
						</li>
						<li class="nav-item"><a><%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "nav-link"  %></a></li>
						<li class="nav-item"><a><%= link_to "Mon compte", user_path(current_user), class: "nav-link"  %></a></li>
							<% else %>
						<li class="nav-item"><a><%= link_to "Se connecter", new_user_session_path, class: "nav-link"  %></a></li>
						<li class="nav-item"><a><%= link_to "S'enregistrer", new_user_registration_path, class: "nav-link"  %></a></li>
							<% end %>
						<li class="nav-item" id="margin_t">
							<a data-scroll class="nav-link btn btn-primary" href="#booking">Réservez un vol</a>
						</li>
					</ul>   
				</div>
			</div>
		</nav>
	</div>

app/views/home/_nos_services.html.erb
	<div id="services">
		<div class="container">
			<div class="center-title">
				<br><br>
				<h2 class="text-black">Pourquoi voyager avec nous ?</h2>

				<p class="text-black-gray"></p>
			</div>
			<div class="row text-center">
				<div class="col-md-4 mb30">
					<%= image_tag('transparence.png', :class => 'img-fluid') %>
					<h4 class="text-black">#Transparence</h4>
					<p id="text_black">
						Commission fixe de 5%. A quel pourcentage se rémunère votre courtier ?
					</p>
				</div>
				<div class="col-md-4 mb30">
					<%= image_tag('dispo.png', :class => 'img-fluid') %>
					<h4 class="text-black">#Disponibilité</h4>
					<p id="text_black">
						Un départ à la dernière minute ? Une question sur un vol ? Nous sommes à votre écoute 24/7
					</p>
				</div>
				<div class="col-md-4 mb30">
					<%= image_tag('confi.png', :class => 'img-fluid') %>
					<h4 class="text-black">#Confidentialité</h4>
					<p id="text_black">
						La confidentialité est l'écrin du bonheur
				</p>
				</div>
				<div class="col-md-4 mb30">
					<%= image_tag('choix.png', :class => 'img-fluid') %>
					<h4 class="text-black">#Choix</h4>
					<p id="text_black">
						Faites le bon choix d'être accompagné à travers une flotte mondiale de plus de 7000 jets
					</p>
				</div>
				<div class="col-md-4 mb30">
					<%= image_tag('traiteur.png', :class => 'img-fluid') %>
					<h4 class="text-black">#Traiteur</h4>
					<p id="text_black">
						Les plus grands traiteurs du monde entier pour vous garantir un voyage gourmand
					</p>
				</div>
				<div class="col-md-4 mb30">
					<%= image_tag('carbon.png', :class => 'img-fluid') %>
					<h4 class="text-black">#Compensation carbonne</h4>
					<p id="text_black">
						En partenariat avec l'association CO2 solidaire, donner un visage humain à votre emprunte carbonne
					</p>
				</div>
			</div>
		</div>
		<br><br><br><br><br><br>
	</div>

app/views/home/_promise.html.erb
<div id="white">
	<div class="center-title">
		<h2 class="text-black">La promesse Stratton</h2>
	</div>

	<h5 id="black_ita_marg">
		<center>
			Réserver un jet privé peut être compliqué. 
			<br>
			À Stratton Jets, nous pensons que cela ne doit plus être le cas. <br>
			C'est pourquoi nous guidons nos clients dans un processus de recherche simple et efficace.
			<br><br>
			Notre objectif : vous offrir une offre juste et précise selon vos besoins.
		</center>
	</h5>
	<br>
</div>

app/views/home/_text_window.html.erb
<div id="vision" class="half-image-content bg-faded">
	<div id="vision2" class="content-img bg-parallax pos-left" data-jarallax='{"speed": 0.2}' style="background: url('<%= asset_path 'contained2.png' %>') no-repeat;">
	</div>
	<div class="container">
		<div class="row">
			<div class="col-lg-5 ml-auto  pt80 pb80">
				<h2>
					Notre vision
					<br>
				</h2>
				<div id="black_italic">

					<h5> "L'histoire est simple, Stratton est né d’un constat qui est le manque de transparence dans l’aviation privée : <br> <br>
						Saviez vous qu'un courtier habituel vous prend entre 10 et 20% de frais de commission à chacun de vos voyages ?
						<br> <br>
						C'est pourquoi, grâce à la technologie Stratton, nous avons décidé de proposer un système de commission fixe de 5%. <br> <br>
						Plus important encore, afin de connaitre enfin les conditions de votre voyage, notre systeme est basé sur une totale transparence. <br> <br>
						Ensemble, nous coupons les intermédiaires ! <br> <br>
						Notre souhait est que vous puissiez choisir et réservez votre jet en sachant le prix exact payé à la compagnie." <br> <br>
					</h5>
					<%= image_tag("sign.png", width: 120, height: 80)%>
					<br><br>
					<h4> John Smith, fondateur de Stratton </h4>

					<br> <br>

				</div>
			</div>
		</div>
	</div>
</div>

app/views/home/button_elevator.html.erb
<div id='contact'>
		<div id="markermap" style="width: 100%;height: 350px;"></div>
	</div>
	<a href="#" class="back-to-top" id="back-to-top"><i class="ti-angle-up"></i></a>