config/routes.rb
Rails.application.routes.draw do

	resources :messages
	root 'home#index'

	devise_for :users, path: 'utilisateur'
	resources :charges, only: [:new, :create, :confirm_page]

	resources :users
	resources :aircraft

	post "/recherche-de-vol", to: "aircraft#search_results", as: :search_results
	get "/mon-vol/:id", to: "aircraft#trip", as: :trip

	get "/aircrafts", to: 'aircraft#index'
	get "/aircraft/:id", to: 'aircraft#show'
	get "/planes", to: 'planes#index'
	get "/confirm_page", to: 'charges#confirm_page'
	get "message_admin", to: 'messages#index_admin'
	get "authentification", to: "users#authentification"
	post "authentification", to: "users#get_authentification"

	as :user do
		get 'users/profile', :to => 'devise/registrations#edit', :as => :user_root
	end
end

app/controllers/charges_controller.rb
require 'gmail'

class ChargesController < ApplicationController

  def new 
  end

  #paiement strip en euro

  def create
    @aircraft = Aircraft.find(params[:aircraft_id])
    @departure_city = params[:departure_city]
    @arrival_city = params[:arrival_city]
    @number_of_passengers = params[:number_of_passengers]
    @date = params[:departure_date]
    @current_user_id = current_user.id
    @user_name = User.find(@current_user_id).last_name
    @user_email = User.find(@current_user_id).email
    @user_phone = User.find(@current_user_id).phone.sub(/^./, '33')
    @amount = @aircraft.trip_cost_with_commission(@departure_city, @arrival_city, @number_of_passengers).to_i * 100
    
    customer = Stripe::Customer.create(:email => params[:stripeEmail], :source  => params[:stripeToken])
    charge = Stripe::Charge.create(:customer    => customer.id, :amount      => @amount, :description => 'Rails Stripe customer', :currency    => 'eur')

    UserFlight.create(
      place_departure: @departure_city, 
      place_arrival: @arrival_city, 
      number_of_people: @number_of_passengers, 
      date_departure: @date,
      flight_price: (@amount / 100), 
      user_id: @current_user_id)
    
    send_mail(@user_email, @user_name, @departure_city, @arrival_city, @number_of_passengers)    

    redirect_to confirm_page_path, notice: "Paiement accepté"

  rescue Stripe::CardError => e
    flash.now[:error] = e.message
    redirect_to aircraft_path
  end

  def send_mail(adresse, nom, depart, destination, nombre_de_passager )
    gmail = Gmail.connect(ENV['ADRESSE'],ENV['MDP'])
    email = gmail.compose do
      to adresse
      subject "Reservation de Jet privé"
      body "Bonjour #{nom},

      Ceci est un mail récapitulatif de votre commande sur Stratton Jets.
      Notre equipe prend en charge votre vol en jet privé au depart de #{depart}, a destination de #{destination} pour #{nombre_de_passager} passager(s).

      John Smith, General Manager"
    end
    email.deliver!
  end

  # def confirm_page

  #   @current_user = User.find(current_user.id)
  #   @current_user_flights = @current_user.user_flights
  #   @last_current_user_flight = @current_user_flights.last
  #   @current_user_id = current_user.id
  #   @user_name_l = User.find(@current_user_id).last_name
  #   @user_name_f = User.find(@current_user_id).first_name
  #   @user_email = User.find(@current_user_id).email
  #   @user_phone = User.find(@current_user_id).phone.sub(/^./, '33') 

  # end

  def confirm_page

    @current_user = User.find(current_user.id)

    @current_user_flights = @current_user.user_flights
    @last_current_user_flight = @current_user_flights.last
    @user_name_l = @current_user.last_name
    @user_name_f = @current_user.first_name
    @user_email = @current_user.email
    @user_phone = @current_user.phone.sub(/^./, '33') 

  end
  


  

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/confirm_page.html.erb
<div class="container-fluid" style="margin-top: 5%">
	<h1>Confirmation de paiement</h1>
	<div class="p-4 rounded border1 mb-3 mt-3 bg-white">
		<div class="padding">
			<a href="#" class="btn btn-sm btn-primary float-right" onclick="window.print();">Print</a>
			<%= image_tag("logo.png", width: 170, height: 40)%>
			<div class="row">
				<div class="col-6">
					<h4 class="fs-1x">Stratton-Jets Inc.</h4>
					<p><a href="index.html">Stratton-Jets.com</a></p>
					<p>Office<br><br>France</p>
					<p>Email: Stratton.jets@gmail.com</p>
				</div>
				<div class="col-6 text-right">
					<p class="fs-1x mt-4">#</p>
					<p></p>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-6">
					<div class="box">
						<strong class="text-muted">TO:</strong>
						<h6><%=@user_name_l %> <%=@user_name_f %></h6>
						<p class="text-muted">Phone:<%=@user_phone %> <br>Email: <%=@user_email %><br></p>
					</div>
				</div>
			</div>
			<p>Order date: <strong><%= @last_current_user_flight.created_at.strftime("%d/%m/%Y") %></strong><br>
				Order status: Reservé
				<br>Order ID: <strong>#</strong>
			</p>
			<div class="table-responsive">
				<table class="table table-bordered white">
					<thead>
						<tr>
							<th style="width: 120px">Ville de depart</th>
							<th style="width: 120px">Ville d'arrivee</th>
							<th style="width: 120px">Date du vol</th>
							<th style="width: 120px">Nombre de passager(s)</th>
							<th></th>
							<th style="width: 140px">PRIX HC</th>
							<th style="width: 90px">TOTAL</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td><%= @last_current_user_flight.place_departure%></td>
							<td><%= @last_current_user_flight.place_arrival%></td>
							<%if flights.date_departure == nil %>
							<td></td>
							<%else%>
							<td><%= @last_current_user_flight.date_departure.strftime("%d/%m/%Y")%></td>
							<%end%>
							<td><%= @last_current_user_flight.number_of_people%></td>
							<td></td>
							<td><%= (@last_current_user_flight.flight_price / 1.05).to_i %>€</td>
							<td><%= @last_current_user_flight.flight_price.to_i %>€</td>

						</tr>
					</tbody>
				</table>
			</div>
			<a><%=link_to "Mon compte", user_path(current_user), class: "btn btn-sm btn-secondary float-right"%></a>
		</div>
	</div>
</div>

app/views/charges/create.html.erb
<div style = "margin-top: 15%">

<h2>Thanks, you paid <strong>$<%= @amount / 100 %></strong>!</h2>

</div>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Montant: 5.00 €</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Un mois d’abonnement !"
          data-amount="500"
          data-locale="auto"></script>
<% end %>


<h2>Merci ! Vous venez de payer <strong>5.00 €</strong> pour faire fondre votre graisse !</h2>